import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/common/Navbar";
import MobileNavbar from "@/common/MobileNavbar";
import AuthanticationProvider from "@/common/AuthanticationContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import MobileTopBar from "@/common/MobileTopbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthanticationProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className=" border-2 hidden md:block lg:-ml-[45px]">
            <Navbar />
          </div>
          <div className=" border-2 block md:hidden ">
            <MobileTopBar />
          </div>

          <div className=" bg-gray-100">
            <ToastContainer />

            {children}
          </div>
          <div className=" md:hidden fixed bottom-0">
            <MobileNavbar />
          </div>
        </body>
      </html>
    </AuthanticationProvider>
  );
}
